spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/soen341
spring.datasource.username=soen341_admin
spring.datasource.password=SOEN341

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql


spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework.jdbc.datasource.init=DEBUG
spring.sql.init.continue-on-error=true


#This is a throwaway test email thing don't reuse this in other projects it won't work
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b78a8284c62a9e
spring.mail.password=9240bb2c9cf1ee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true